### PR TITLE
Added CDR Reciver Client, moved the Session Receiver Client to the Re…

### PR DESCRIPTION
**Pull request by chargePanelAndreas**
I noticed that I made a misstake in a previous pull request and placed the session Receiver client in the sender directory. This pull request corrects that and adds the CDR Receiver client.

### CODE REVIEW

**Comment by mrbig** [comment]
For me it seems that you just started your branch a commit earlier than your previous work. In Commit 3fa50a66 you already moved the Sessions client into the Receiver directory.

Would it be possible to rebase this branch on top of v2.2.1-refactor-commands? That would remove the merge conflicts

**Comment by chargePanelAndreas** [comment]
I did not see that commit (it's by another company that is our OCPI client), sure I can rebase it but I cant see the branch you are referencing, did you push it to github?

**Comment by mrbig** [comment]
@chargePanelAndreas sorry, I did not look at the names :) The other branch is from chiarito you mentined earlier. He did almost exactly the same change you did.
However he did not add the cdr client, so those changes are highly appreciated

**Comment by mrbig** [comment]
@chargePanelAndreas I have merge the other pull request, so you could rebase your changes on the top of the v2.1.1 branch if it is ok for you

**Comment by mrbig** [comment]
@chargePanelAndreas never mind I managed to merge your changes with the ones from @chiarito 
You did almost identically the same changes, there were only a few conflicts.
You should take a look at the v2.2.1 branch now, because there are plenty of clients ready now.

**Pull request merged**
